### ISSUE TITLE
식단표 업데이트 문제

### ISSUE THREAD

**Issue by BlueTomcat1** [bunubbv/Chalimpyo#1]
1-2반 컴퓨터인데 대략 2주정도 전부터 식단표가 제대로 업데이트가 안되네요

**Comment by bunubbv** [comment]
확인해보겠습니다. 업데이트 과정 중 문제가 생긴 것 같은데 수정해서 월요일날 반영하겠습니다.

**Comment by bunubbv** [comment]
제가 계속 확인해봤는데 저희 반이나 다른 반에서도 잘 동작하고, 업데이트도 잘 되어서 특별한 문제가 없는 것으로 보입니다. 혹시 아직도 작동이 안 되나요?

**Comment by BlueTomcat1** [comment]
내일 등교해서 다시 확인해보겠습니다. 감사합니다

2023년 6월 7일 (수) 오후 5:37, 권중혁 ***@***.***>님이 작성:

**Comment by BlueTomcat1** [comment]
다음과 같이 업데이트가 제대로 이루어지지 않습니다. 가끔씩 정상작동 되기도 하는데 보통은 이 상태네요. 따로 네트워크 문제도 없습니다.

2023년 6월 7일 (수) 오후 5:37, 권중혁 ***@***.***>님이 작성:

**Comment by bunubbv** [comment]
시험기간이라 답장이 늦었습니다. 저번에 실제로 교실에 가서 확인해봤는데, 네트워크 오류 등으로 인해 겉으로는 정상적인 파일으로 보이나 실제 내용이 없는 빈 파일이 다운로드 되었습니다. 원래 파일이 제대로 다운로드 되지 않은 경우 오류가 발생하고 멈춰야 하나 파일 자체는 존재했기에 발견하지 못했고 결국 업데이트가 되지 않는 과정이 반복된 것으로 보입니다.

업데이트 구조를 조금 더 안정적인 방식으로 변경하고 오류 체크, 무결성 검사 등의 기능을 추가한 뒤 업데이트를 진행하겠습니다.

**Comment by bunubbv** [comment]
가능하다면 업데이트를 진행하기 전까지 스킨 우클릭 > 닫기를 눌러 해당 스킨을 잠시 비활성화 해 주세요. 현재는 무한정 업데이트가 반복되는 상태라 클라우드 쪽에서 트래픽을 막을 수도 있고, 로컬 컴퓨터에도 부하가 걸릴 수 있습니다.

**Comment by BlueTomcat1** [comment]
며칠 전부터 비활성화 된 것인지 식단표는 아예 표시되지 않는데 이러면 상관없을까요?


2023년 6월 12일 (월) 오후 4:10, 권중혁 ***@***.***>님이 작성:

**Comment by bunubbv** [comment]
아예 안 나오는 상황이면 상관 없을 듯 하네요.

**Comment by gravitykwon** [comment]
시험이 끝나서 일단 업데이트는 할 예정인데, 급식 API가 8월 16일까지 작동하지 않아 다른 방법을 한 번 알아보겠습니다.

**Comment by bunubbv** [comment]
스킨 리팩토링 및 업데이트 완료했습니다.

**Comment by Doiram** [comment]
자동 업데이트가 안 되어서 어짜피 월요일 날 반마다 가서 다시 세팅해야 하는데, 하는 김에 같이 업데이트 하겠습니다.

**Comment by bunubbv** [comment]
급식 정보가 여전히 나오지 않고 있으나, 이는 학교 측에서 급식 정보를 업로드하지 않아서 그렇습니다. 스킨이나 API의 문제는 아닌 것으로 확인됩니다.

실제로 다른 학교로 변경하거나, 시간을 과거로 설정하면 정상적으로 정보가 나오는 것을 확인했습니다. 식단표를 수동으로 업데이트 하거나 나이스에 급식 정보를 등록해야 하는데, 이는 단기간 내 해결될 수 있는 문제는 아닌 것 같습니다. 일단 이슈는 오픈 상태로 유지하겠습니다.

**Comment by bunubbv** [comment]
급식 정보 등록 및 정상 작동 확인, 이슈 닫습니다.
